---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install distro packages
  package:
    name: "{{ ironic_inspector_packages_list }}"
    state: "{{ ironic_inspector_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in ironic_inspector_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: ironic_inspector_developer_mode | bool

- name: Retrieve checksum for venv download
  uri:
    url: "{{ ironic_inspector_venv_download_url | replace('tgz', 'checksum') }}"
    return_content: yes
  register: ironic_inspector_venv_checksum
  when: ironic_inspector_venv_download | bool

- name: Attempt venv download
  get_url:
    url: "{{ ironic_inspector_venv_download_url }}"
    dest: "/var/cache/{{ ironic_inspector_venv_download_url | basename }}"
    checksum: "sha1:{{ ironic_inspector_venv_checksum.content | trim }}"
  register: ironic_inspector_get_venv
  when: ironic_inspector_venv_download | bool

- name: Remove existing venv
  file:
    path: "{{ ironic_inspector_bin | dirname }}"
    state: absent
  when: ironic_inspector_get_venv  is changed

- name: Create ironic venv dir
  file:
    path: "{{ ironic_inspector_bin | dirname }}"
    state: directory
    mode: "0755"
  register: ironic_inspector_venv_dir
  when: ironic_inspector_get_venv  is changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ ironic_inspector_venv_download_url | basename }}"
    dest: "{{ ironic_inspector_bin | dirname }}"
    copy: "no"
  when: ironic_inspector_get_venv  is changed
  notify: Restart ironic inspector services

- name: Install pip packages
  pip:
    name: "{{ ironic_inspector_pip_packages }}"
    state: "{{ ironic_inspector_pip_package_state }}"
    virtualenv: "{{ ironic_inspector_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ ironic_inspector_developer_mode | ternary(pip_install_developer_constraints | default('--constraint /opt/developer-pip-constraints.txt'), '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  when: ironic_inspector_get_venv | failed or ironic_inspector_get_venv | skipped
  notify: Restart ironic inspector services

- name: Remove python from path first (CentOS, openSUSE)
  file:
    path:  "{{ ironic_inspector_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr in ['yum', 'zypper']
    - ironic_inspector_get_venv  is changed

# NOTE(odyssey4me):
# We reinitialize the venv to ensure that the right
# version of python is in the venv, but we do not
# want virtualenv to also replace pip, setuptools
# and wheel so we tell it not to.
# We do not use --always-copy for CentOS/SuSE due
# to https://github.com/pypa/virtualenv/issues/565
- name: Update virtualenv path
  shell: |
    find {{ ironic_inspector_bin }} -name \*.pyc -delete
    sed -si '1s/^.*python.*$/#!{{ ironic_inspector_bin | replace ('/','\/') }}\/python/' {{ ironic_inspector_bin }}/*
    virtualenv {{ ironic_inspector_bin | dirname }} \
        {{ (ansible_pkg_mgr == 'apt') | ternary('--always-copy', '') }} \
        --no-pip \
        --no-setuptools \
        --no-wheel
  when: ironic_inspector_get_venv  is changed
  tags:
    - skip_ansible_lint

- name: Install optional pip packages
  pip:
    name: "{{ ironic_inspector_requires_pip_packages }}"
    state: "{{ ironic_inspector_pip_package_state }}"
  register: install_optional_packages
  until: install_optional_packages is success
  retries: 5
  delay: 2

- name: Record the venv tag deployed
  ini_file:
    dest: "/etc/ansible/facts.d/openstack_ansible.fact"
    section: ironic
    option: venv_tag
    value: "{{ ironic_inspector_venv_tag }}"
